import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loading=document.querySelector('#loading'),site=document.querySelector('#invite'),code=new URLSearchParams(location.search).get('code');
const $=s=>document.querySelector(s), setText=(s,v)=>{const e=$(s);if(e)e.textContent=v??''}, escapeUrl=u=>String(u||'').replace(/"/g,'%22');
function revealSite(){loading.classList.add('hidden');site.classList.remove('hidden');requestAnimationFrame(()=>document.querySelectorAll('.reveal').forEach(e=>observer.observe(e)));setupPageExperience()}
function setLink(s,u){const e=$(s);if(!e)return;if(u){e.href=u;e.classList.remove('hidden')}else e.classList.add('hidden')}
let qrReady;function ensureQr(){if(window.QRCode)return Promise.resolve();if(qrReady)return qrReady;qrReady=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});return qrReady}
async function renderQr(selector,value,size=164){const target=$(selector);if(!target)return;try{await ensureQr();target.innerHTML='';const canvas=document.createElement('canvas');target.appendChild(canvas);await new Promise((resolve,reject)=>window.QRCode.toCanvas(canvas,value,{width:size,margin:1,color:{dark:'#26322d',light:'#ffffff'}},err=>err?reject(err):resolve()))}catch{target.innerHTML='<span class="tiny">QR no disponible</span>'}}
function setupCountdown(raw){const box=$('#countdown');if(!box||!raw)return;const d=new Date(raw);if(Number.isNaN(d.getTime()))return;box.hidden=false;const tick=()=>{const r=d.getTime()-Date.now();if(r<=0){['#days','#hours','#minutes','#seconds'].forEach(s=>setText(s,'0'));return}const sec=Math.floor(r/1000);setText('#days',Math.floor(sec/86400));setText('#hours',Math.floor(sec%86400/3600));setText('#minutes',Math.floor(sec%3600/60));setText('#seconds',sec%60)};tick();setInterval(tick,1000)}
function setupGallery(images,captions){const cards=[...document.querySelectorAll('.gallery-card')],lightbox=$('#lightbox'),art=$('#lightbox-art'),caption=$('#lightbox-caption');cards.forEach((card,i)=>{const u=images[i];if(u){card.style.backgroundImage=`linear-gradient(180deg,rgba(20,24,22,.02),rgba(20,24,22,.3)),url("${escapeUrl(u)}")`;card.classList.add('has-photo')}else card.classList.add('gallery-empty');card.querySelector('.photo-caption')?.classList.toggle('hidden',!u);card.addEventListener('click',()=>{if(!u)return;art.style.backgroundImage=`url("${escapeUrl(u)}")`;caption.textContent=captions[i]||'Un momento especial';lightbox.classList.remove('hidden');document.body.style.overflow='hidden'})});const shut=()=>{lightbox?.classList.add('hidden');document.body.style.overflow=''};$('#lightbox-close')?.addEventListener('click',shut);lightbox?.addEventListener('click',e=>{if(e.target===lightbox)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape')shut()})}
function celebrate(){const b=document.createElement('div');b.className='celebration';for(let i=0;i<18;i++){const p=document.createElement('span');p.textContent=i%2?'✦':'·';p.style.setProperty('--x',`${(Math.random()-.5)*280}px`);p.style.setProperty('--y',`${-80-Math.random()*180}px`);p.style.setProperty('--r',`${(Math.random()-.5)*240}deg`);b.appendChild(p)}document.body.appendChild(b);setTimeout(()=>b.remove(),1100)}
function openPass(name,count,inviteCode){setText('#pass-name',name);setText('#pass-people',`${count} ${count===1?'persona':'personas'} confirmada${count===1?'':'s'}`);setText('#pass-code',inviteCode);const accessUrl=`${location.origin}${location.pathname.replace(/invitacion\.html$/,'')}index.html?code=${encodeURIComponent(inviteCode)}`;renderQr('#pass-qr',accessUrl,188);$('#pass-modal')?.classList.remove('hidden');document.body.style.overflow='hidden'}
function closePass(){$('#pass-modal')?.classList.add('hidden');document.body.style.overflow=''}
function printPass(){document.body.classList.add('printing-pass');$('#pass-modal')?.classList.remove('hidden');setTimeout(()=>{window.print();setTimeout(()=>document.body.classList.remove('printing-pass'),500)},80)}
function setupPageExperience(){const pages=[...site.querySelectorAll('.page')],dots=$('#page-dots');if(!pages.length)return;dots.innerHTML=pages.map((p,i)=>`<button class="page-dot" type="button" data-dot="${i}" aria-label="Ir a ${p.dataset.pageLabel||`página ${i+1}`}"></button>`).join('');const go=index=>pages[Math.max(0,Math.min(pages.length-1,index))].scrollIntoView({behavior:'smooth',block:'start'});document.querySelectorAll('[data-next-page]').forEach(b=>b.addEventListener('click',()=>go(pages.indexOf(b.closest('.page'))+1)));document.querySelectorAll('[data-go-page]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.goPage))));dots.querySelectorAll('[data-dot]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.dot))));const update=idx=>{dots.querySelectorAll('.page-dot').forEach((d,i)=>d.classList.toggle('active',i===idx));document.querySelectorAll('[data-go-page]').forEach(b=>b.classList.toggle('active',Number(b.dataset.goPage)===idx));const bar=$('#progress-bar');if(bar)bar.style.width=`${(idx/(pages.length-1||1))*100}%`};const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const idx=pages.indexOf(e.target);if(idx>=0)update(idx)}}),{root:site,threshold:.65});pages.forEach(p=>io.observe(p));let lock=false;site.addEventListener('wheel',e=>{if(lock||document.querySelector('.pass-modal:not(.hidden),.lightbox:not(.hidden)'))return;if(Math.abs(e.deltaY)<18)return;if(e.target.closest('button,a,input,textarea,select,label,details,.floating-nav'))return;const current=Math.round(site.scrollTop/site.clientHeight),next=e.deltaY>0?current+1:current-1;if(next<0||next>=pages.length)return;e.preventDefault();lock=true;go(next);setTimeout(()=>lock=false,650)},{passive:false});let touchStartY=null;site.addEventListener('touchstart',e=>touchStartY=e.touches[0].clientY,{passive:true});site.addEventListener('touchend',e=>{if(touchStartY===null)return;const dy=touchStartY-e.changedTouches[0].clientY;if(Math.abs(dy)>45){const current=Math.round(site.scrollTop/site.clientHeight),next=dy>0?current+1:current-1;if(next>=0&&next<pages.length)go(next)}touchStartY=null},{passive:true})}
async function updateRsvp(msg,count,status){msg.textContent='Guardando…';const{data,error}=await supabase.rpc('update_rsvp',{p_code:code,p_confirmed_guests:count,p_status:status});const r=Array.isArray(data)?data[0]:data;if(error||!r?.success){msg.textContent=r?.message||error?.message||'No se pudo guardar la respuesta.';return null}msg.textContent=status==='confirmed'?`Perfecto. Confirmaste ${r.confirmed_guests} ${r.confirmed_guests===1?'persona':'personas'}.`:'Hemos guardado tu respuesta. Gracias por avisarnos.';return r}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{root:site,threshold:.12});
async function init(){if(!code){loading.textContent='Esta invitación necesita un código.';return}const{data,error}=await supabase.rpc('get_public_invitation',{p_code:code});const i=Array.isArray(data)?data[0]:data;if(error||!i){loading.textContent='Esta invitación no está disponible.';return}
const textMap={
 '#hero-eyebrow':'hero_eyebrow','#home-subtitle':'home_subtitle','#welcome-text':'welcome_text','#welcome-eyebrow':'welcome_eyebrow','#welcome-title':'welcome_title',
 '#story-eyebrow':'story_eyebrow','#story-title':'story_title','#story-text':'story_text','#story-signature':'story_signature',
 '#event-eyebrow':'event_eyebrow','#event-title':'event_title','#event-intro':'event_intro','#reception-time':'reception_time','#reception-title':'reception_title','#reception-description':'reception_description','#ceremony-time':'ceremony_time','#ceremony-title':'ceremony_title','#ceremony-description':'ceremony_description','#dress-eyebrow':'dress_eyebrow','#dress-code':'dress_code','#dress-description':'dress_description',
 '#gallery-eyebrow':'gallery_eyebrow','#gallery-title':'gallery_title','#gallery-description':'gallery_description','#location-eyebrow':'location_eyebrow','#details-arrival-title':'details_arrival_title','#details-arrival-description':'details_arrival_description','#details-dress-title':'details_dress_title','#details-dress-description':'details_dress_description','#details-gifts-title':'details_gifts_title','#details-gifts-description':'details_gifts_description',
 '#gift-eyebrow':'gift_eyebrow','#gift-title':'gift_title','#gift-text':'gift_text','#faq-eyebrow':'faq_eyebrow','#faq-title':'faq_title','#faq-q1':'faq_q1','#faq-a1':'faq_a1','#faq-q2':'faq_q2','#faq-a2':'faq_a2','#faq-q3':'faq_q3','#faq-a3':'faq_a3',
 '#rsvp-eyebrow':'rsvp_eyebrow','#rsvp-title':'rsvp_title','#rsvp-text':'rsvp_text','#rsvp-prompt':'rsvp_prompt','#rsvp-confirm-label':'rsvp_confirm_label','#rsvp-decline-label':'rsvp_decline_label','#access-eyebrow':'access_eyebrow','#access-title':'access_title','#access-description':'access_description','#final-eyebrow':'final_eyebrow','#final-title':'final_title','#final-description':'final_description'};
Object.entries(textMap).forEach(([s,k])=>{if(i[k]!==null&&i[k]!==undefined&&i[k]!=='' )setText(s,i[k])});
setText('#guest-name',i.guest_name);setText('#rsvp-guest',i.guest_name);setText('#couple-names',i.couple_names);setText('#footer-couple',i.couple_names);setText('#hero-date',i.event_date);setText('#venue-name',i.venue_name);setText('#venue-address',i.venue_address);setText('#parking-text',i.parking_text);setText('#total-guests',i.total_guests);setText('#code',i.code);
setLink('#maps-link',i.maps_url);setLink('#waze-link',i.waze_url);setLink('#gift-link',i.gift_url);if(i.hero_image_url)$('#inicio').style.backgroundImage=`url("${escapeUrl(i.hero_image_url)}")`;
const caps=[i.gallery_caption_1,i.gallery_caption_2,i.gallery_caption_3,i.gallery_caption_4];caps.forEach((v,n)=>setText(`#gallery-caption-${n+1}`,v||`Momento ${n+1}`));setupCountdown(i.event_date);const accessUrl=`${location.origin}${location.pathname.replace(/invitacion\.html$/,'')}index.html?code=${encodeURIComponent(i.code)}`;renderQr('#qr',accessUrl,164);setupGallery([i.gallery_image_1_url,i.gallery_image_2_url,i.gallery_image_3_url,i.gallery_image_4_url],caps);
let count=Math.max(1,Math.min(Number(i.confirmed_guests||1),Number(i.total_guests)));setText('#count',count);const confirmed=i.rsvp_status==='confirmed'&&Number(i.confirmed_guests)>0;if(confirmed){$('#confirmed-badge')?.classList.remove('hidden');$('#view-pass')?.classList.remove('hidden')}
const minus=$('#minus'),plus=$('#plus'),confirm=$('#confirm'),decline=$('#decline'),msg=$('#rsvp-message');const sync=()=>{setText('#count',count);minus.disabled=count<=1;plus.disabled=count>=Number(i.total_guests)};minus.addEventListener('click',()=>{count=Math.max(1,count-1);sync()});plus.addEventListener('click',()=>{count=Math.min(Number(i.total_guests),count+1);sync()});if(i.rsvp_confirm_label)setText('#confirm',i.rsvp_confirm_label);if(i.rsvp_decline_label)setText('#decline',i.rsvp_decline_label);
confirm.addEventListener('click',async()=>{confirm.disabled=true;decline.disabled=true;const r=await updateRsvp(msg,count,'confirmed');if(r){$('#confirmed-badge')?.classList.remove('hidden');$('#view-pass')?.classList.remove('hidden');celebrate();setTimeout(()=>openPass(i.guest_name,Number(r.confirmed_guests),i.code),300)}confirm.disabled=false;decline.disabled=false});decline.addEventListener('click',async()=>{if(!confirm('¿Seguro que deseas indicar que no podrás asistir?'))return;confirm.disabled=true;decline.disabled=true;await updateRsvp(msg,0,'declined');$('#confirmed-badge')?.classList.add('hidden');$('#view-pass')?.classList.add('hidden');confirm.disabled=false;decline.disabled=false});
$('#view-pass')?.addEventListener('click',()=>openPass(i.guest_name,count,i.code));$('#view-pass-2')?.addEventListener('click',()=>openPass(i.guest_name,Math.max(1,Number(i.confirmed_guests||count)),i.code));$('#print-pass')?.addEventListener('click',printPass);$('#pass-print')?.addEventListener('click',printPass);$('#pass-close')?.addEventListener('click',closePass);$('#pass-close-2')?.addEventListener('click',closePass);$('#pass-modal')?.addEventListener('click',e=>{if(e.target.id==='pass-modal')closePass()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePass()});sync();revealSite()}
init();