import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loading=document.querySelector('#loading'),site=document.querySelector('#invite');
const code=new URLSearchParams(location.search).get('code');
const $=s=>document.querySelector(s); const setText=(s,v)=>{const e=$(s);if(e)e.textContent=v??''};
const escapeUrl=u=>String(u||'').replace(/"/g,'%22');
function revealSite(){loading.classList.add('hidden');site.classList.remove('hidden');requestAnimationFrame(()=>document.querySelectorAll('.reveal').forEach(e=>observer.observe(e)))}
function setLink(s,u){const e=$(s);if(!e)return;if(u){e.href=u;e.classList.remove('hidden')}else e.classList.add('hidden')}
function renderQr(v){const t=$('#qr');if(!t)return;t.innerHTML='';const c=document.createElement('canvas');t.appendChild(c);const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js';script.onload=()=>window.QRCode?.toCanvas?window.QRCode.toCanvas(c,v,{width:164,margin:1},err=>{if(err)t.innerHTML='<span class="tiny">QR no disponible</span>';}):t.innerHTML='<span class="tiny">QR no disponible</span>';document.head.appendChild(script)}
function setupCountdown(raw){const box=$('#countdown');if(!box||!raw)return;const d=new Date(raw);if(Number.isNaN(d.getTime()))return;box.hidden=false;const tick=()=>{const r=d.getTime()-Date.now();if(r<=0){['#days','#hours','#minutes','#seconds'].forEach(s=>setText(s,'0'));return}const sec=Math.floor(r/1000);setText('#days',Math.floor(sec/86400));setText('#hours',Math.floor(sec%86400/3600));setText('#minutes',Math.floor(sec%3600/60));setText('#seconds',sec%60)};tick();setInterval(tick,1000)}
function setupGallery(images){const cards=[...document.querySelectorAll('.gallery-card')],lightbox=$('#lightbox'),art=$('#lightbox-art'),caption=$('#lightbox-caption'),close=$('#lightbox-close');if(!cards.length||!lightbox||!art||!caption||!close)return;const captions=['Un momento para recordar','Juntos','Nuestro día','Siempre'];cards.forEach((card,i)=>{const u=images[i];if(u){card.style.backgroundImage=`linear-gradient(180deg,rgba(20,24,22,.03),rgba(20,24,22,.28)),url("${escapeUrl(u)}")`;card.classList.add('has-photo');card.querySelector('span')?.classList.add('hidden')}else{card.classList.add('gallery-empty')}card.addEventListener('click',()=>{if(!u)return;art.style.backgroundImage=`url("${escapeUrl(u)}")`;caption.textContent=captions[i]||'Un momento especial';lightbox.classList.remove('hidden');document.body.style.overflow='hidden'})});const shut=()=>{lightbox.classList.add('hidden');document.body.style.overflow=''};close.addEventListener('click',shut);lightbox.addEventListener('click',e=>{if(e.target===lightbox)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape')shut()})}
function celebrate(){const b=document.createElement('div');b.className='celebration';for(let i=0;i<18;i++){const p=document.createElement('span');p.textContent=i%2?'✦':'·';p.style.setProperty('--x',`${(Math.random()-.5)*280}px`);p.style.setProperty('--y',`${-80-Math.random()*180}px`);p.style.setProperty('--r',`${(Math.random()-.5)*240}deg`);b.appendChild(p)}document.body.appendChild(b);setTimeout(()=>b.remove(),1100)}
async function updateRsvp(msg,count,status){msg.textContent='Guardando…';const{data,error}=await supabase.rpc('update_rsvp',{p_code:code,p_confirmed_guests:count,p_status:status});const r=Array.isArray(data)?data[0]:data;if(error||!r?.success){msg.textContent=r?.message||error?.message||'No se pudo guardar la respuesta.';return false}msg.textContent=status==='confirmed'?`¡Perfecto! Confirmaste ${r.confirmed_guests} ${r.confirmed_guests===1?'persona':'personas'}.`:'Hemos registrado que no podrás acompañarnos.';return true}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});
async function init(){if(!code){loading.textContent='Esta invitación necesita un código.';return}const{data,error}=await supabase.rpc('get_public_invitation',{p_code:code});const i=Array.isArray(data)?data[0]:data;if(error||!i){loading.textContent='Esta invitación no está disponible.';return}
  setText('#guest-name',i.guest_name);setText('#rsvp-guest',i.guest_name);setText('#couple-names',i.couple_names);setText('#footer-couple',i.couple_names);setText('#hero-date',i.event_date);setText('#welcome-text',i.welcome_text);setText('#reception-time',i.reception_time);setText('#ceremony-time',i.ceremony_time);setText('#venue-name',i.venue_name);setText('#venue-address',i.venue_address);setText('#parking-text',i.parking_text);setText('#faq-parking',i.parking_text);setText('#dress-code',i.dress_code);setText('#dress-code-alt',i.dress_code);setText('#gift-text',i.gift_text);setText('#total-guests',i.total_guests);setText('#code',i.code);setText('#faq-children',i.allow_children?'Sí. Esta invitación permite niños.':'Esta invitación está configurada sin niños.');
  setLink('#maps-link',i.maps_url);setLink('#waze-link',i.waze_url);setLink('#gift-link',i.gift_url);
  if(i.hero_image_url) $('.hero').style.backgroundImage=`url("${escapeUrl(i.hero_image_url)}")`;
  setupCountdown(i.event_date);renderQr(`${location.origin}${location.pathname}?code=${encodeURIComponent(i.code)}`);setupGallery([i.gallery_image_1_url,i.gallery_image_2_url,i.gallery_image_3_url,i.gallery_image_4_url]);
  let count=Math.max(1,Math.min(Number(i.confirmed_guests||1),Number(i.total_guests)));setText('#count',count);const minus=$('#minus'),plus=$('#plus'),confirm=$('#confirm'),decline=$('#decline'),msg=$('#rsvp-message');
  const sync=()=>{setText('#count',count);minus.disabled=count<=1;plus.disabled=count>=i.total_guests};minus.addEventListener('click',()=>{count--;sync()});plus.addEventListener('click',()=>{count++;sync()});confirm.addEventListener('click',async()=>{confirm.disabled=true;decline.disabled=true;const ok=await updateRsvp(msg,count,'confirmed');if(ok){celebrate();$('.access')?.scrollIntoView({behavior:'smooth'})}confirm.disabled=false;decline.disabled=false});decline.addEventListener('click',async()=>{if(!window.confirm('¿Seguro que deseas indicar que no podrás asistir?'))return;confirm.disabled=true;decline.disabled=true;await updateRsvp(msg,0,'declined');confirm.disabled=false;decline.disabled=false});sync();revealSite()}
init();
